'use client';

import { useState, useEffect, useRef } from 'react';
import { Location, TacoBellLocation } from '@/types';
import { useRoutePlanner } from '@/hooks/useRoutePlanner';
import MapView from '@/components/MapView';
import LocationSearch from '@/components/LocationSearch';
import WaypointList from '@/components/WaypointList';
import ShareButton from '@/components/ShareButton';
import { formatDistance } from '@/lib/googleMaps';
import AutoRoutePlannerModal from '@/components/AutoRoutePlannerModal';
import { APIProvider } from '@vis.gl/react-google-maps';

export default function Home() {
  const {
    startPoint,
    endPoint,
    waypoints,
    routeData,
    isCalculating,
    error,
    setStartPoint,
    setEndPoint,
    addWaypoint,
    removeWaypoint,
    reorderWaypoints,
    clearRoute,
    loadAutoGeneratedRoute,
  } = useRoutePlanner();

  const [endSameAsStart, setEndSameAsStart] = useState(false);
  const [waypointSearchValue, setWaypointSearchValue] = useState<Location | null>(null);
  const [isAutoModalOpen, setIsAutoModalOpen] = useState(false);
  const manuallyUncheckedRef = useRef(false);

  // Sync endPoint with startPoint when checkbox is checked
  useEffect(() => {
    if (endSameAsStart && startPoint) {
      setEndPoint(startPoint);
      manuallyUncheckedRef.current = false; // Reset when syncing
    }
  }, [endSameAsStart, startPoint, setEndPoint]);

  // Auto-check the checkbox if start and end points are the same
  useEffect(() => {
    if (startPoint && endPoint) {
      const areSame =
        startPoint.lat === endPoint.lat &&
        startPoint.lng === endPoint.lng &&
        startPoint.address === endPoint.address;
      // Auto-check if they're the same but checkbox is unchecked
      // Don't auto-check if user manually unchecked it
      if (areSame && !endSameAsStart && !manuallyUncheckedRef.current) {
        setEndSameAsStart(true);
      }
      // Reset the manual uncheck flag if points change
      if (!areSame) {
        manuallyUncheckedRef.current = false;
      }
    } else if (!startPoint || !endPoint) {
      // Uncheck if either point is cleared
      if (endSameAsStart) {
        setEndSameAsStart(false);
      }
      manuallyUncheckedRef.current = false;
    }
  }, [startPoint, endPoint, endSameAsStart]);

  const apiKey = process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY;

  if (!apiKey) {
    return (
      <div className="min-h-screen flex items-center justify-center" style={{ background: 'linear-gradient(135deg, #36399a 0%, #a77bca 100%)' }}>
        <div className="text-center p-8 bg-white rounded-lg shadow-md max-w-md">
          <h1 className="text-2xl font-bold mb-4" style={{ color: '#36399a' }}>
            Google Maps API Key Required
          </h1>
          <p className="text-gray-600 mb-4">
            Please set your Google Maps API key in the <code className="bg-gray-100 px-2 py-1 rounded">.env.local</code> file:
          </p>
          <code className="block bg-gray-100 p-3 rounded text-sm text-left">
            NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=your_api_key_here
          </code>
          <p className="text-sm text-gray-500 mt-4">
            See README.md for setup instructions.
          </p>
        </div>
      </div>
    );
  }

  return (
    <APIProvider apiKey={apiKey}>
      <div className="min-h-screen flex flex-col bg-gray-50">
        {/* Header */}
        <header className="bg-white border-b border-gray-200 shadow-sm" style={{ background: 'linear-gradient(to right, #36399a, #a77bca)' }}>
          <div className="max-w-7xl mx-auto px-4 py-4">
            <h1 className="text-2xl font-bold text-white" style={{ fontFamily: 'var(--font-taco-bell-bold)' }}>Taco Bell 50K Route Planner</h1>
            <p className="text-sm text-white/90 mt-1">
              Plan your own Taco Bell 50K route with waypoints and distance tracking. Run Más!
            </p>
          </div>
        </header>

        {/* Main Content */}
        <main className="flex-1 flex flex-col lg:flex-row max-w-[1920px] mx-auto w-full">
          {/* Left Column: Route Edit Tools */}
          <div className="lg:w-1/4 bg-gray-50 h-auto lg:h-[calc(100vh-120px)] border-r border-gray-200 flex flex-col">
            <div className="flex-1 overflow-y-auto p-4 space-y-4">
              {/* Total Distance Display */}
              {routeData && (
                <div className="bg-white rounded-lg shadow-md p-4 border border-gray-200 mb-4">
                  <h3 className="text-sm font-semibold text-gray-700 mb-1">Total Distance</h3>
                  <p className="text-2xl font-semibold" style={{ color: '#36399a' }}>
                    {isCalculating ? (
                      <span className="text-gray-400">Calculating...</span>
                    ) : (
                      formatDistance(routeData.totalDistance)
                    )}
                  </p>
                </div>
              )}

              {/* Start Point */}
              <div>
                <label className="block text-sm font-semibold text-gray-700 mb-2">
                  Start Point
                </label>
                <LocationSearch
                  placeholder="Search for start location..."
                  onLocationSelect={setStartPoint}
                  value={startPoint}
                />
              </div>

              {/* End Point Same as Start Checkbox */}
              <div className="flex items-center">
                <input
                  type="checkbox"
                  id="endSameAsStart"
                  checked={endSameAsStart}
                  onChange={(e) => {
                    const checked = e.target.checked;
                    setEndSameAsStart(checked);
                    if (!checked) {
                      manuallyUncheckedRef.current = true;
                    } else {
                      manuallyUncheckedRef.current = false;
                    }
                  }}
                  className="w-4 h-4 border-gray-300 rounded focus:ring-2"
                  style={{ accentColor: '#36399a' }}
                />
                <label
                  htmlFor="endSameAsStart"
                  className="ml-2 text-sm text-gray-700 cursor-pointer"
                >
                  End point same as start point
                </label>
              </div>

              {/* End Point */}
              {!endSameAsStart && (
                <div>
                  <label className="block text-sm font-semibold text-gray-700 mb-2">
                    End Point
                  </label>
                  <LocationSearch
                    placeholder="Search for end location..."
                    onLocationSelect={setEndPoint}
                    value={endPoint}
                  />
                </div>
              )}

              {/* Auto-Generate 50K Route Button */}
              <div className="pt-2 pb-2">
                <button
                  onClick={() => setIsAutoModalOpen(true)}
                  className="w-full px-4 py-2 text-white rounded-lg transition-colors font-medium text-sm"
                  style={{ backgroundColor: '#36399a' }}
                  onMouseEnter={(e) => e.currentTarget.style.backgroundColor = '#2d3180'}
                  onMouseLeave={(e) => e.currentTarget.style.backgroundColor = '#36399a'}
                >
                  🚀 Auto-Generate 50K Route
                </button>
              </div>

              {/* Add Waypoint */}
              <div>
                <label className="block text-sm font-semibold text-gray-700 mb-2">
                  Add Waypoint
                </label>
                <LocationSearch
                  placeholder="Search for waypoint location..."
                  onLocationSelect={(location) => {
                    if (startPoint || endPoint) {
                      addWaypoint(location);
                      setWaypointSearchValue(null);
                    }
                  }}
                  value={waypointSearchValue}
                />
                <p className="text-xs text-gray-500 mt-1">
                  Add waypoints to your route
                </p>
              </div>

              {/* Waypoint List */}
              {waypoints.length > 0 && (
                <div>
                  <h3 className="text-sm font-semibold text-gray-700 mb-2">
                    Waypoints ({waypoints.length})
                  </h3>
                  <WaypointList
                    waypoints={waypoints}
                    routeSegments={routeData?.segments || []}
                    onReorder={reorderWaypoints}
                    onRemove={removeWaypoint}
                  />
                </div>
              )}

              {/* Error Display */}
              {error && (
                <div className="rounded-lg p-3" style={{ backgroundColor: '#fee01240', border: '1px solid #ef1897' }}>
                  <p className="text-sm" style={{ color: '#ef1897' }}>{error}</p>
                </div>
              )}
            </div>

            {/* Share Button and Clear Route Button - Pinned to Bottom */}
            <div className="p-4 border-t border-gray-200 bg-gray-50 space-y-3">
              <ShareButton
                startPoint={startPoint}
                endPoint={endPoint}
                waypoints={waypoints}
              />
              {(startPoint || endPoint || waypoints.length > 0) && (
                <button
                  onClick={() => {
                    clearRoute();
                    setEndSameAsStart(false);
                    manuallyUncheckedRef.current = false;
                  }}
                  className="w-full px-4 py-2 text-white rounded-lg transition-colors font-medium text-sm"
                  style={{ backgroundColor: '#ef1897' }}
                  onMouseEnter={(e) => e.currentTarget.style.backgroundColor = '#d01685'}
                  onMouseLeave={(e) => e.currentTarget.style.backgroundColor = '#ef1897'}
                >
                  Clear Route
                </button>
              )}
            </div>
          </div>

          {/* Map */}
          <div className="flex-1 h-[600px] lg:h-[calc(100vh-120px)] bg-white">
            <MapView
              startPoint={startPoint}
              endPoint={endPoint}
              waypoints={waypoints}
            />
          </div>
        </main>

        {/* Auto Route Planner Modal */}
        <AutoRoutePlannerModal
          isOpen={isAutoModalOpen}
          onClose={() => setIsAutoModalOpen(false)}
          onRouteFound={(route: TacoBellLocation[]) => {
            loadAutoGeneratedRoute(route);
            setEndSameAsStart(true);
            manuallyUncheckedRef.current = false;
          }}
        />
      </div>
    </APIProvider>
  );
}
